version: '3.8'

networks:
  terrerov_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  traefik_certs:
  pihole_config:
  pihole_dnsmasq:
  pihole_custom_dns:

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    networks:
      terrerov_net:
        ipv4_address: 172.20.0.53
    ports:
      - "8080:80/tcp"
    environment:
      TZ: 'UTC'
      WEBPASSWORD: ${ADMIN_PASSWORD}
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
      DNSMASQ_LISTENING: 'all'
      VIRTUAL_HOST: 'pihole.terrerov.com'
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
      - ./pihole/custom.list:/etc/pihole/custom.list:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.terrerov.com`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.middlewares=secure-headers@file"
    restart: unless-stopped

  traefik:
    image: traefik:v2.10
    container_name: traefik
    networks:
      - terrerov_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - traefik_certs:/etc/traefik/acme
      - ./etc/traefik/dynamic:/etc/traefik/dynamic:ro
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_TOKEN}
      - CLOUDFLARE_EMAIL=${EMAIL}
      - EMAIL=${EMAIL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.terrerov.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=auth,secure-headers@file"
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.auth.basicauth.users=admin:${TRAEFIK_PASSWORD}"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: nginx
    networks:
      - terrerov_net
    ports:
      - "8081:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`www.terrerov.com`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=cloudflare"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.middlewares=secure-headers@file"
    restart: unless-stopped